export interface Team {
    id: string;
    name: string;
    isStillIn: boolean;
  }

export const TEAMS = {
  ALGERIA: { id: 'algeria', name: 'Algeria', isStillIn: true },
  ARGENTINA: { id: 'argentina', name: 'Argentina', isStillIn: true },
  AUSTRALIA: { id: 'australia', name: 'Australia', isStillIn: true },
  AUSTRIA: { id: 'austria', name: 'Austria', isStillIn: true },
  BELGIUM: { id: 'belgium', name: 'Belgium', isStillIn: true },
  BOSNIA_HERZEGOVINA: { id: 'bosnia-and-herzegovina', name: 'Bosnia and Herzegovina', isStillIn: true },
  BRAZIL: { id: 'brazil', name: 'Brazil', isStillIn: true },
  CANADA: { id: 'canada', name: 'Canada', isStillIn: true },
  CAPE_VERDE: { id: 'cape-verde', name: 'Cape Verde', isStillIn: true },
  COLOMBIA: { id: 'colombia', name: 'Colombia', isStillIn: true },
  CROATIA: { id: 'croatia', name: 'Croatia', isStillIn: true },
  CURACAO: { id: 'curacao', name: 'Curaçao', isStillIn: true },
  CZECH_REPUBLIC: { id: 'czech-republic', name: 'Czech Republic', isStillIn: true },
  DR_CONGO: { id: 'dominican-republic-congo', name: 'Dominican Republic Congo', isStillIn: true },
  ECUADOR: { id: 'ecuador', name: 'Ecuador', isStillIn: true },
  EGYPT: { id: 'egypt', name: 'Egypt', isStillIn: true },
  ENGLAND: { id: 'england', name: 'England', isStillIn: true },
  FRANCE: { id: 'france', name: 'France', isStillIn: true },
  GERMANY: { id: 'germany', name: 'Germany', isStillIn: true },
  GHANA: { id: 'ghana', name: 'Ghana', isStillIn: true },
  HAITI: { id: 'haiti', name: 'Haiti', isStillIn: true },
  IRAN: { id: 'iran', name: 'Iran', isStillIn: true },
  IRAQ: { id: 'iraq', name: 'Iraq', isStillIn: true },
  IVORY_COAST: { id: 'ivory-coast', name: 'Ivory Coast', isStillIn: true },
  JAPAN: { id: 'japan', name: 'Japan', isStillIn: true },
  JORDAN: { id: 'jordan', name: 'Jordan', isStillIn: true },
  MEXICO: { id: 'mexico', name: 'Mexico', isStillIn: true },
  MOROCCO: { id: 'morocco', name: 'Morocco', isStillIn: true },
  NETHERLANDS: { id: 'netherlands', name: 'Netherlands', isStillIn: true },
  NEW_ZEALAND: { id: 'new-zealand', name: 'New Zealand', isStillIn: true },
  NORWAY: { id: 'norway', name: 'Norway', isStillIn: true },
  PANAMA: { id: 'panama', name: 'Panama', isStillIn: true },
  PARAGUAY: { id: 'paraguay', name: 'Paraguay', isStillIn: true },
  PORTUGAL: { id: 'portugal', name: 'Portugal', isStillIn: true },
  QATAR: { id: 'qatar', name: 'Qatar', isStillIn: true },
  SAUDI_ARABIA: { id: 'saudi-arabia', name: 'Saudi Arabia', isStillIn: true },
  SCOTLAND: { id: 'scotland', name: 'Scotland', isStillIn: true },
  SENEGAL: { id: 'senegal', name: 'Senegal', isStillIn: true },
  SOUTH_AFRICA: { id: 'south-africa', name: 'South Africa', isStillIn: true },
  SOUTH_KOREA: { id: 'south-korea', name: 'South Korea', isStillIn: true },
  SPAIN: { id: 'spain', name: 'Spain', isStillIn: true },
  SWEDEN: { id: 'sweden', name: 'Sweden', isStillIn: true },
  SWITZERLAND: { id: 'switzerland', name: 'Switzerland', isStillIn: true },
  TUNISIA: { id: 'tunisia', name: 'Tunisia', isStillIn: true },
  TURKIYE: { id: 'turkiye', name: 'Türkiye', isStillIn: true },
  URUGUAY: { id: 'uruguay', name: 'Uruguay', isStillIn: true },
  USA: { id: 'usa', name: 'USA', isStillIn: true },
  UZBEKISTAN: { id: 'uzbekistan', name: 'Uzbekistan', isStillIn: true },
};